networks:
  default:
    name: sql-server
    driver: bridge

services:
  sql-server:
    container_name: sql-server
    hostname: sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    restart: unless-stopped
    volumes:
      - ${VOLUME_PATH}/data:/var/opt/mssql/data
      - ${VOLUME_PATH}/log:/var/opt/mssql/log
      - ${VOLUME_PATH}/secrets:/var/opt/mssql/secrets
      - ${VOLUME_PATH}/backup:/var/opt/mssql/backup
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      MSSQL_PID: ${MSSQL_PID}
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P ${SA_PASSWORD} -Q 'SELECT 1' -C"]
      interval: 10s
      timeout: 5s
      retries: 5


