version: "3.7"

services:
  node-red:
    container_name: node-red
    image: nodered/node-red:3.1.3
    restart: unless-stopped
    volumes:
      - ./data:/data
    network_mode: bridge
    ports:
      - 80:1880
volumes:
  node-red:
    name: node-red
