version: "3.8"

services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dockge:/data
    environment:
      # Tell Dockge where is your stacks directory
      - DOCKGE_STACKS_DIR=dockge/stacks
    networks:
      - dockge

networks:
  dockge:

volumes:
  dockge:
    name: dockge
